### ISSUE TITLE
How old are you, on your birthday?

### ISSUE THREAD

**Issue by larpSTATGL** [anhoej/cprr#1]
Hi Jacob,

I wonder about this result: 

> cprr::age("0312227199","2023-12-03")  # fiktive pnr
[1] 0.9993155

Should this rather be =1 ? One year old on your 1-year birthday?

Thank you, for sharing a great package

Lars

**Comment by anhoej** [comment]
Thank you, Lars. Well spotted.

The correct answer is of course 1 year. However, calculating accurate age in decimal years is not a simple task. I am not sure it is even possible because years are of varying length. So cprr simply calculates the difference between date of birth and the current date as number of days divided by 365.25, which is good enough for most purposes. The inaccuracy amounts to at most less than one day (~0.003 years).

If you need more precision, I suggest you calculate age in days - or minutes or seconds ;-)

One might of course want to calculate age in whole years by fiddling with the year and day-of-year parts. But for statistical analyses, I see no reason to throw away the information carried by the decimals.

Kind regards
Jacob

**Comment by larpSTATGL** [comment]
Thank you for a quick reply. Actually I need less accuracy. Perhaps as simple as: 

> round(cprr::age("0312227199","2023-12-03"),0)
[1] 1

Lars
